'use client';

import React from 'react';
import { Sparkles, Info } from 'lucide-react';

interface AITransparencyBadgeProps {
  model?: string;
  tokensUsed?: number;
  className?: string;
  compact?: boolean;
}

export default function AITransparencyBadge({
  model = 'Gemini 2.5 Flash',
  tokensUsed,
  className = '',
  compact = false,
}: AITransparencyBadgeProps) {
  if (compact) {
    return (
      <div
        className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-white/5 border border-white/10 text-xs text-gray-400 font-medium ${className}`}
        title="AI-generated response by Placely Kiro. Please verify critical information."
      >
        <Sparkles className="w-3.5 h-3.5 text-[#FF7A00]" />
        <span>AI-generated · {model}</span>
        {tokensUsed !== undefined && tokensUsed > 0 && (
          <span className="text-gray-500">({tokensUsed} tokens)</span>
        )}
      </div>
    );
  }

  return (
    <div
      className={`flex items-center justify-between gap-2 px-3 py-1.5 rounded-lg bg-black/40 border border-white/10 text-xs text-gray-400 ${className}`}
    >
      <div className="flex items-center gap-2">
        <Sparkles className="w-3.5 h-3.5 text-[#FF7A00]" />
        <span>
          <strong className="text-gray-300 font-medium">AI-Generated Analysis</strong> · Kiro ({model})
        </span>
      </div>
      <div className="flex items-center gap-2 text-gray-500 text-[11px]">
        {tokensUsed !== undefined && tokensUsed > 0 && (
          <span>{tokensUsed.toLocaleString()} tokens</span>
        )}
        <span className="flex items-center gap-1 text-gray-500" title="AI output is generated by a large language model and should be verified for critical placement decisions.">
          <Info className="w-3 h-3" />
          <span>Verify AI output</span>
        </span>
      </div>
    </div>
  );
}
